export const SET_PLAY_PHASE = "SET_PLAY_PHASE";
export const UPDATE_PLAY_PHASE = "UPDATE_PLAY_PHASE";
export const GET_PLAY_PHASE = "GET_PLAY_PHASE";
export const SET_SELECTED_CATEGORIES = "SET_SELECTED_CATEGORIES";
export const UPDATE_SELECTED_CATEGORIES = "UPDATE_SELECTED_CATEGORIES";
export const DELETE_SELECTED_CATEGORY = "DELETE_SELECTED_CATEGORY";
export const REMOVE_SELECTED_CATEGORY = "REMOVE_SELECTED_CATEGORY";
export const GET_SELECTED_CATEGORIES = "GET_SELECTED_CATEGORIES";
