export default {
  PLAY: {
    SET_PLAY_PHASE: "SET_PLAY_PHASE",
    UPDATE_PLAY_PHASE: "UPDATE_PLAY_PHASE",
    GET_PLAY_PHASE: "GET_PLAY_PHASE",
  },
  CATEGORIES: {
    SET_SELECTED_CATEGORIES: "SET_SELECTED_CATEGORIES",
    UPDATE_SELECTED_CATEGORIES: "UPDATE_SELECTED_CATEGORIES",
    DELETE_SELECTED_CATEGORY: "DELETE_SELECTED_CATEGORY",
    REMOVE_SELECTED_CATEGORY: "REMOVE_SELECTED_CATEGORY",
    GET_SELECTED_CATEGORIES: "GET_SELECTED_CATEGORIES",
  },
  GAME: {
    SET_PROGRESS: "SET_PROGRESS",
    SET_QUESTION: "SET_QUESTION",
    SET_ANSWERS: "SET_ANSWERS",
    UPDATE_PROGRESS: "UPDATE_PROGRESS",
    FETCH_TRIVIA: "FETCH_TRIVIA",
    GET_PROGRESS: "GET_PROGRESS",
    GET_QUESTION: "GET_QUESTION",
    GET_ANSWERS: "GET_ANSWERS",
  },
  TIMER: {
    SET_SHOW_CORRECT_ANSWER_TIMER: "SET_SHOW_CORRECT_ANSWER_TIMER",
    UPDATE_SHOW_CORRECT_ANSWER_TIMER: "UPDATE_SHOW_CORRECT_ANSWER_TIMER",
    GET_SHOW_CORRECT_ANSWER_TIMER: "GET_SHOW_CORRECT_ANSWER_TIMER",
  },
};
